let create_specs = [
  
    [
        {
          "cat": "computer",
          "product_id": 0,
          "title": "Nerdlane",
          "image": "https://iili.io/HhRY6mu.webp",
          "small_img1": "https://iili.io/HhRYZqQ.webp",
          "small_img2": "https://iili.io/HhRcFwu.webp",
          "small_img3": "https://iili.io/HhRcC6Q.webp",
          "desc": "Blue Full Frame Rectangle",
          "rupees": "1000",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 1,
          "title": "IZIBUKO",
          "image": "https://iili.io/HhRcPix.webp",
          "small_img1": "https://iili.io/HhRcQUB.webp",
          "small_img2": "https://iili.io/HhRlqOX.webp",
          "small_img3": "https://iili.io/HhRlqOX.webp",
          "desc": "Pink Full Frame Oval",
          "rupees": "1000",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 2,
          "title": "ALFProduct",
          "image": "https://iili.io/HhR0dhu.webp",
          "small_img1": "https://iili.io/HhR0nkP.webp",
          "small_img2": "https://iili.io/HhR0nkP.webp",
          "small_img3": "https://iili.io/HhR0nkP.webp",
          "desc": "Black and Blue Full Frame Rectangle",
          "rupees": "850",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 3,
          "title": "IZIBUKO",
          "image": "https://iili.io/HhRcPix.webp",
          "small_img1": "https://iili.io/HhRcQUB.webp",
          "small_img2": "https://iili.io/HhRlqOX.webp",
          "small_img3": "https://iili.io/HhRlqOX.webp",
          "desc": "Pink Full Frame Oval",
          "rupees": "1000",
          "status": false
        },
        {
          "cat": "computer",
          "product_id": 4,
          "title": "ALFProduct",
          "image": "https://iili.io/H8PuYeS.webp",
          "small_img1": "https://iili.io/H8Pu0Xe.webp",
          "small_img2": "https://iili.io/H8PuGqb.webp",
          "small_img3": "https://iili.io/H8PukLg.webp",
          "desc": "Purple and Black Frame Rectangle",
          "rupees": "1300",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 5,
          "title": "Nerdlane",
          "image": "https://iili.io/HhRY6mu.webp",
          "small_img1": "https://iili.io/HhRYZqQ.webp",
          "small_img2": "https://iili.io/HhRcFwu.webp",
          "small_img3": "https://iili.io/HhRcC6Q.webp",
          "desc": "Blue Full Frame Rectangle",
          "rupees": "1000",
          "status": false
        },
        {
          "cat": "computer",
          "product_id": 6,
          "title": "IZIBUKO",
          "image": "https://iili.io/HhRcPix.webp",
          "small_img1": "https://iili.io/HhRcQUB.webp",
          "small_img2": "https://iili.io/HhRlqOX.webp",
          "small_img3": "https://iili.io/HhRlqOX.webp",
          "desc": "Pink Full Frame Oval",
          "rupees": "1000",
          "status": false
        },
        {
          "cat": "computer",
          "product_id": 7,
          "title": "",
          "image": "https://iili.io/H8PAQ9V.webp",
          "small_img1": "https://iili.io/H8PADt1.webp",
          "small_img2": "https://iili.io/H8PRHKJ.webp",
          "small_img3": "https://iili.io/H8PRFAN.webp",
          "desc": "Tiger style Full Frame Rectangle",
          "rupees": "1200",
          "status": false
        },
        {
          "cat": "computer",
          "product_id": 8,
          "title": "https://iili.io/H8P5ozP.webp",
          "image": "https://iili.io/H8PR1lj.webp",
          "small_img1": "https://iili.io/H8PRVRV.webp",
          "small_img2": "https://iili.io/H8PRme2.webp",
          "small_img3": "https://iili.io/H8P5ozP.webp",
          "desc": "Brown Full Frame Rectangle",
          "rupees": "1000",
          "status": false
        },
        {
          "cat": "computer",
          "product_id": 9,
          "title": "Nerdlane",
          "image": "https://iili.io/H8PusIt.webp",
          "small_img1": "https://iili.io/H8PuDEG.webp",
          "small_img2": "https://iili.io/H8PAHpS.webp",
          "small_img3": "https://iili.io/H8PAcaR.webp",
          "desc": "Orange Full Frame Oval",
          "rupees": "2000",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 10,
          "title": "IZIBUKO",
          "image": "https://iili.io/HhRcPix.webp",
          "small_img1": "https://iili.io/HhRcQUB.webp",
          "small_img2": "https://iili.io/HhRlqOX.webp",
          "small_img3": "https://iili.io/HhRlqOX.webp",
          "desc": "Pink Full Frame Oval",
          "rupees": "1000",
          "status": false
        },
        {
          "cat": "computer",
          "product_id": 11,
          "title": "ALFProduct",
          "image": "https://iili.io/H8PAQ9V.webp",
          "small_img1": "https://iili.io/H8PADt1.webp",
          "small_img2": "https://iili.io/H8PRHKJ.webp",
          "small_img3": "https://iili.io/H8PRFAN.webp",
          "desc": "Tiger style Full Frame Rectangle",
          "rupees": "1100",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 12,
          "title": "IZIBUKO",
          "image": "https://iili.io/HhRcPix.webp",
          "small_img1": "https://iili.io/HhRcQUB.webp",
          "small_img2": "https://iili.io/HhRlqOX.webp",
          "small_img3": "https://iili.io/HhRlqOX.webp",
          "desc": "Pink Full Frame Oval",
          "rupees": "1000",
          "status": false
        },
        {
          "cat": "computer",
          "product_id": 13,
          "title": "Nerdlane",
          "image": "https://iili.io/H8PR1lj.webp",
          "small_img1": "https://iili.io/H8PRVRV.webp",
          "small_img2": "https://iili.io/H8PRme2.webp",
          "small_img3": "https://iili.io/H8P5ozP.webp",
          "desc": "Brown Full Frame Rectangle",
          "rupees": "1500",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 14,
          "title": "ALFProduct",
          "image": "https://iili.io/H8P7Hpp.webp",
          "small_img1": "https://iili.io/H8P7KCX.webp",
          "small_img2": "https://iili.io/H8P776u.webp",
          "small_img3": "https://iili.io/H8P7k9R.webp",
          "desc": "Yellow tiger Full Frame Rectangle",
          "rupees": "1125",
          "status": false
        },
        {
          "cat": "computer",
          "product_id": 15,
          "title": "Nerdlane",
          "image": "https://iili.io/H8P04Yg.webp",
          "small_img1": "https://iili.io/H8P19vs.webp",
          "small_img2": "https://iili.io/H8P1fGS.webp",
          "small_img3": "https://iili.io/H8P176P.webp",
          "desc": "Violet Full Frame Round",
          "rupees": "2500",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 16,
          "title": "ALFProduct",
          "image": "https://iili.io/H8P7Hpp.webp",
          "small_img1": "https://iili.io/H8P7KCX.webp",
          "small_img2": "https://iili.io/H8P776u.webp",
          "small_img3": "https://iili.io/H8P7k9R.webp",
          "desc": "Yellow tiger Full Frame Round",
          "rupees": "1125",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 17,
          "title": "Nerdlane",
          "image": "https://iili.io/H8P5lII.webp",
          "small_img1": "https://iili.io/H8P5M1s.webp",
          "small_img2": "https://iili.io/H8P58Be.webp",
          "small_img3": "https://iili.io/H8P54Yx.webp",
          "desc": "Blue and Grey Full Frame Rectangle",
          "rupees": "3000",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 18,
          "title": "IZIBUKO",
          "image": "https://iili.io/H8PAwFf.webp",
          "small_img1": "https://iili.io/H8PAk92.webp",
          "small_img2": "https://iili.io/H8PA8w7.webp",
          "small_img3": "https://iili.io/H8PAPFj.webp",
          "desc": "Glossy Brown frame rectangle",
          "rupees": "990",
          "status": true
        },
        {
          "cat": "computer",
          "product_id": 19,
          "title": "ALFProduct",
          "image": "https://iili.io/H8PTgO7.webp",
          "small_img1": "https://iili.io/H8PuHWg.webp",
          "small_img2": "https://iili.io/H8PufJp.webp",
          "small_img3": "https://iili.io/H8Puu1f.webp",
          "desc": "Brown Full Frame Oval",
          "rupees": "550",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 20,
          "title": "IZIBUKO",
          "image": "https://iili.io/HSVnm3x.webp",
          "small_img1": "https://iili.io/HSVoB3v.webp",
          "small_img2": "https://iili.io/HSVozuI.webp",
          "small_img3": "https://iili.io/HSVoRGs.webp",
          "desc": "Green Full Frame Glass Round",
          "rupees": "2000",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 21,
          "title": "ALFProduct",
          "image": "https://iili.io/HSVoEw7.webp",
          "small_img1": "https://iili.io/HSVoWMu.webp",
          "small_img2": "https://iili.io/HSVopPs.webp",
          "small_img3": "https://iili.io/HSVxBVe.webp",
          "desc": "Lemon Yellow Frame Rectangle",
          "rupees": "1000",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 22,
          "title": "Nerdlane",
          "image": "https://iili.io/HSVxWbI.webp",
          "small_img1": "https://iili.io/HSVxkgf.webp",
          "small_img2": "https://iili.io/HSVxsqu.webp",
          "small_img3": "https://iili.io/HSVzxLX.webp",
          "desc": "Grey Full Frame oval",
          "rupees": "1100",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 23,
          "title": "Nerdlane",
          "image": "https://iili.io/HSVzR2f.webp",
          "small_img1": "https://iili.io/HSVzpaf.webp",
          "small_img2": "https://iili.io/HSVIJu2.webp",
          "small_img3": "https://iili.io/HSVIIwB.webp",
          "desc": "Grey Full Frame oval",
          "rupees": "990",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 24,
          "title": "ALFProduct",
          "image": "https://iili.io/HSVI09R.webp",
          "small_img1": "https://iili.io/HSVT2Hv.webp",
          "small_img2": "https://iili.io/HSVTOqF.webp",
          "small_img3": "https://iili.io/HSVuurg.webp",
          "desc": "Magenda Full Frame Oval",
          "rupees": "700",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 25,
          "title": "ALFProduct",
          "image": "https://iili.io/HSVuhvf.webp",
          "small_img1": "https://iili.io/HSVuS4e.webp",
          "small_img2": "https://iili.io/HSVutG1.webp",
          "small_img3": "https://iili.io/HSVAacu.webp",
          "desc": "Indigo Blue Full Frame Oval",
          "rupees": "2010",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 26,
          "title": "Nerdlane",
          "image": "https://iili.io/HSVAgVI.webp",
          "small_img1": "https://iili.io/HSVAQRf.webp",
          "small_img2": "https://iili.io/HSVRCiP.webp",
          "small_img3": "https://iili.io/HSVRzUg.webp",
          "desc": "Blue Full Frame Round",
          "rupees": "899",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 27,
          "title": "IZIBUKO",
          "image": "https://iili.io/HSV5HLN.webp",
          "small_img1": "https://iili.io/HSV5iuf.webp",
          "small_img2": "https://iili.io/HSV5LZl.webp",
          "small_img3": "https://iili.io/HSV7BF1.webp",
          "desc": "Yellow With Blue Frame Round",
          "rupees": "1500",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 28,
          "title": "Nerdlane",
          "image": "https://iili.io/HSV7vNj.webp",
          "small_img1": "https://iili.io/HSVYJUX.webp",
          "small_img2": "https://iili.io/HSVYCs2.webp",
          "small_img3": "https://iili.io/HSVYRbj.webp",
          "desc": "Magenda Full Frame Oval",
          "rupees": "650",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 29,
          "title": "Nerdlane",
          "image": "https://iili.io/HSVYlqB.webp",
          "small_img1": "https://iili.io/HSVYVea.webp",
          "small_img2": "https://iili.io/HSVYOqN.webp",
          "small_img3": "https://iili.io/HSVYUes.webp",
          "desc": "Grey Full Frame oval",
          "rupees": "999",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 30,
          "title": "IZIBUKO",
          "image": "https://iili.io/HSVa5YX.webp",
          "small_img1": "https://iili.io/HSVa0Q4.webp",
          "small_img2": "https://iili.io/HSVa8GV.webp",
          "small_img3": "https://iili.io/HSVag3P.webp",
          "desc": "Yellow With Pink Frame Round",
          "rupees": "1800",
          "status": true
        },
        {
          "cat": "sun",
          "product_id": 31,
          "title": "ALFProduct",
          "image": "https://iili.io/HSVYQr7.webp",
          "small_img1": "https://iili.io/HSVadBV.webp",
          "small_img2": "https://iili.io/HSVaqkg.webp",
          "small_img3": "https://iili.io/HSVaxQR.webp",
          "desc": "Lite Blue Full Frame Oval",
          "rupees": "1111",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 32,
          "title": "IZIBUKO",
          "image": "https://iili.io/HSN6sTl.webp",
          "small_img1": "https://iili.io/HSN6QQS.webp",
          "small_img2": "https://iili.io/HSNP2jV.webp",
          "small_img3": "https://iili.io/HSNPcas.webp",
          "desc": "Violet Full Frame Oval metal",
          "rupees": "1200",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 33,
          "title": "Nerdlane",
          "image": "https://iili.io/HSNPEu4.jpg",
          "small_img1": "https://iili.io/HSNPyPt.jpg",
          "small_img2": "https://iili.io/HSNPNcu.jpg",
          "small_img3": "https://iili.io/HSNidSs.jpg",
          "desc": "Blue Full Frame Rectangle",
          "rupees": "2999",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 34,
          "title": "ALFProduct",
          "image": "https://iili.io/HSNirb4.jpg",
          "small_img1": "https://iili.io/HSNiQ19.jpg",
          "small_img2": "https://iili.io/HSNsehQ.jpg",
          "small_img3": "https://iili.io/HSNsehQ.jpg",
          "desc": "Green Full Frame Glass Rectangle",
          "rupees": "1500",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 35,
          "title": "ALFProduct",
          "image": "https://iili.io/HSNsPyJ.jpg",
          "small_img1": "https://iili.io/HSNLHyG.jpg",
          "small_img2": "https://iili.io/HSNL2j4.jpg",
          "small_img3": "https://iili.io/HSNLfGS.jpg",
          "desc": "Sand Full Frame Round",
          "rupees": "1600",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 36,
          "title": "Nerdlane",
          "image": "https://iili.io/HSNLuZQ.jpg",
          "small_img1": "https://iili.io/HSNLl8g.jpg",
          "small_img2": "https://iili.io/HSNLXMN.jpg",
          "small_img3": "https://iili.io/HSNLXMN.jpg",
          "desc": "Classic Black Full Frame Rectangle",
          "rupees": "1899",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 37,
          "title": "ALFProduct",
          "image": "https://iili.io/HSN6Be4.webp",
          "small_img1": "https://iili.io/HSN6lIV.webp",
          "small_img2": "https://iili.io/HSN6ehN.webp",
          "small_img3": "https://iili.io/HSN66vf.webp",
          "desc": "Chocolate Brown Full Frame Round",
          "rupees": "500",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 38,
          "title": "ALFProduct",
          "image": "https://iili.io/HSNLgol.webp",
          "small_img1": "https://iili.io/HSNLQHu.webp",
          "small_img2": "https://iili.io/HSNQFRa.webp",
          "small_img3": "https://iili.io/HSNQfDv.webp",
          "desc": "Black Full Frame Rectangle",
          "rupees": "550",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 39,
          "title": "IZIBUKO",
          "image": "https://iili.io/HSNQxfI.webp",
          "small_img1": "https://iili.io/HSNQARs.webp",
          "small_img2": "https://iili.io/HSNQYx4.webp",
          "small_img3": "https://iili.io/HSNQaWl.webp",
          "desc": "Brown Full Frame Rectangle",
          "rupees": "600",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 40,
          "title": "Nerdlane",
          "image": "https://iili.io/HSNQMJe.webp",
          "small_img1": "https://iili.io/HSNQwWQ.webp",
          "small_img2": "https://iili.io/HSNQU5g.webp",
          "small_img3": "https://iili.io/HSNQpmG.webp",
          "desc": "Chocolate Brown Full Frame Oval",
          "rupees": "666",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 41,
          "title": "IZIBUKO",
          "image": "https://iili.io/HSNiFRf.jpg",
          "small_img1": "https://iili.io/HSNiuHb.jpg",
          "small_img2": "https://iili.io/HSNik0X.jpg",
          "small_img3": "https://iili.io/HSNiuHb.jpg",
          "desc": "Sky Blue Full Frame Round",
          "rupees": "450",
          "status": true
        },
        {
          "cat": "power",
          "product_id": 42,
          "title": "ALFProduct",
          "image": "https://iili.io/HSN4PWP.webp",
          "small_img1": "https://iili.io/HSN4Q0g.webp",
          "small_img2": "https://iili.io/HSN4pbp.webp",
          "small_img3": "https://iili.io/HSN631n.webp",
          "desc": "Tiger Brown Power glasses oval",
          "rupees": "520",
          "status": true
        }
      ]
]



if (localStorage.getItem("create_specs")) {
  // return;
  console.log("sdgdvf");
} else {
  localStorage.setItem("create_specs", JSON.stringify(create_specs));
  console.log("yes");
}

